### 계정 생성

POST {{url}}member-management/members
Content-Type: application/json

{
    "id": "byeo-chan",
    "password": "1234",
    "passwordConfirm": "1234",
    "email": "qufnr@kakao.com",
    "name": "룩벼쟝",
    "bio": "<p>저에요</p>"
}

### 계정 수정
PUT {{url}}member-management/members
Content-Type: application/json
Authorization: Bearer {{bearer.access}}

{
    "name": "아리텐동dd",
    "bio": "<p></p>"
}

### 계정 ID 또는 이메일 사용 가능 여부 확인
GET {{url}}member-management/members/can-use?type=ID&value=aris

### 계정 ID 찾기
POST {{url}}member-management/members/forget/id
Content-Type: application/json

{
    "value": "aris1"
}

### 계정 비밀번호 찾기
POST {{url}}member-management/members/forget/password
Content-Type: application/json

{
    "value": "aris1"
}

### 비밀번호 변경
PUT {{url}}member-management/members/password
Content-Type: application/json
X-BServer-Password-Authorization: Bearer {{bearer.password}}

{
    "key": "9XhDEC",
    "password": "12345",
    "passwordConfirm": "12345"
}