### 계정 생성

POST {{url}}member-management/members
Content-Type: application/json

{
    "id": "aris1",
    "password": "1234",
    "passwordConfirm": "1234",
    "email": "qufnr@kakao.com",
    "name": "아리텐동",
    "bio": "<p></p>"
}

### 계정 수정
PUT {{url}}member-management/members
Content-Type: application/json
Authorization: Bearer {{bearer.access}}

{
    "name": "아리텐동스",
    "bio": "<p></p>"
}

### 계정 ID 또는 이메일 사용 가능 여부 확인
GET {{url}}member-management/members/can-use?type=ID&value=aris

### 계정 ID 또는 비밀번호 찾기
PUT {{url}}member-management/members/forget
Content-Type: application/json

{
    "type": "ID",
    "value": "aris1"
}