### ID 인증

POST {{url}}member-management/signs/id
Content-Type: application/json

{
    "value": "aris1"
}

### 로그인

POST {{url}}member-management/signs
Content-Type: application/json
X-BServer-Sign-Authorization: Bearer {{bearer.sign}}

{
    "password": "1234"
}