### 계정 생성

POST {{url}}member-management/members
Content-Type: application/json

{
    "id": "aris1",
    "password": "1234",
    "passwordConfirm": "12",
    "email": "aris.tendou@kivotos.jp",
    "name": "아리텐동",
    "bio": "<p></p>"
}

### 계정 수정
PUT {{url}}member-management/members
Content-Type: application/json
Authorization: Bearer {{bearer.sign}}

{
    "name": "아리텐동1",
    "bio": "<p></p>"
}

### 계정 ID 또는 이메일 사용 가능 여부 확인
GET {{url}}member-management/members/can-use?type=ID&value=aris